const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
const DESTROY_PRODUCT_SUCCESS = 'DESTROY_PRODUCT_SUCCESS';
const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
const SET_FAVORITE_PRODUCT = 'SET_FAVORITE_PRODUCT';
const UNSET_FAVORITE_PRODUCT = 'UNSET_FAVORITE_PRODUCT'

export {
  LOAD_PRODUCTS_SUCCESS,
  DESTROY_PRODUCT_SUCCESS,
  CREATE_PRODUCT_SUCCESS,
  SET_FAVORITE_PRODUCT,
  UNSET_FAVORITE_PRODUCT
}
